[build]
builder = "nixpacks"

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
PYTHON_VERSION = "3.11.7"
