services:
  # Backend API Service
  - type: web
    name: drivenow-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads/vehicles uploads/documents uploads/payments
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8000
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: drivenow-frontend
    env: static
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://drivenow-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

